// clients/angular-reference/src/example-dashboard.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { StandardApiClient } from './standard-api-client';
import { StandardResultQueryState, completedState, loadingState } from './standard-result-query';

interface DashboardSummary {
  title: string;
  totalItems: number;
}

@Component({
  selector: 'genkidama-example-dashboard',
  standalone: true,
  imports: [CommonModule],
  template: `
    <p *ngIf="state.loading">Loading...</p>
    <p *ngIf="state.problem">{{ state.problem.message }}</p>
    <section *ngIf="state.value">
      <h1>{{ state.value.title }}</h1>
      <p>Total items: {{ state.value.totalItems }}</p>
    </section>
  `
})
export class ExampleDashboardComponent implements OnInit {
  protected state: StandardResultQueryState<DashboardSummary> = loadingState();
  private readonly client = inject(StandardApiClient);

  public ngOnInit(): void {
    this.client
      .getResult<DashboardSummary>('dashboard/summary')
      .subscribe(result => this.state = completedState(result));
  }
}

// clients/react-reference/src/ExampleDashboard.tsx
import { useMemo } from 'react';
import { StandardApiClient } from './standardApiClient';
import { useStandardResultQuery } from './useStandardResultQuery';

interface DashboardSummary {
  title: string;
  totalItems: number;
}

export function ExampleDashboard(): JSX.Element {
  const client = useMemo(() => new StandardApiClient({ baseUrl: '/api' }), []);
  const state = useStandardResultQuery<DashboardSummary>(client, 'dashboard/summary');

  if (state.loading) return <p>Loading...</p>;
  if (state.problem) return <p>{state.problem.message}</p>;

  return (
    <section>
      <h1>{state.value?.title ?? 'Dashboard'}</h1>
      <p>Total items: {state.value?.totalItems ?? 0}</p>
    </section>
  );
}
